Upload version for review
BohdanLeasoft/magentoGPE pull request #1
Opened 2021-11-29 13:42 UTC by BohdanLeasoft

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft requested changes
Good job! in general all looks good, but also there are some moments that can be improved, also pay attention on klarnapaylater/klarnapaynow/klarnadirectdebit payment methods, in plugin we have KlarnaDirect and KlarnaDirectDebit, probably KlarnaDirect should be KlarnaPayNow and its images and xml files also should be named KlarnaPayNow.  Take a look on [emspay](https://dev.online.emspay.eu/rest-api/server-to-server) dev docs, there is some additional information about Klarna payment methods.

Plugin structure looks good👍

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Block/Info/Afterpay.php
> +        return $this->testModus;
_"modus"_ is a correct naming? looks like it should be module/modules, but I'm not sure

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Block/Info/Klarna.php
> +}
the same question about naming (_"modus"_)

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/AbstractPayment.php
> +        if ($this->method_code == Afterpay::METHOD_CODE || $this->method_code == Klarna::METHOD_CODE)
You can use _in_array_ function instead of condition with OR.
`if (in_array($this->method_code, [Afterpay::METHOD_CODE, Klarna::METHOD_CODE])) {}`
It will be a bit shorter, more readable, and we will avoid repeat of `$this->method_code ==`.

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/AbstractPayment.php
> +            );
`$ingOrder` is a wrong variable name, ING is the bank that was before EMS, and now we define variables like this with ginger prefix, $gingerOrder.

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ConfigRepositoryBuilder.php
> +    }
There are unnecessary 'else' statements, it can be simplified in the next way:

```
        if ($method == Klarna::METHOD_CODE && $testFlag == 'klarna')
        {
            return $this->getKlarnaTestApiKey($storeId, true);
        }

        if($method == Afterpay::METHOD_CODE && $testFlag == 'afterpay')
        {
            return $this->getAfterpayTestApiKey($storeId, true);
        }

        return $this->getApiKey($storeId);
```

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ConfigRepositoryBuilder.php
> +            return current($transaction['transactions'])['reason'];
`reason` should be replaced to `customer_message`

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ConfigRepositoryBuilder.php
> +        if ($transaction['status'] == 'error' && !empty(current($transaction['transactions'])['reason'])) {
if statement can be simplified, ` if ($transaction['status'] == 'error' && current($transaction['transactions'])['reason'])`

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ConfigRepositoryBuilder.php
> +        }
Unnecessary elseif, and code duplications it can be simplified in the next way
```
if ($transaction['status'] == 'cancelled')
        {
            $method = current($transaction['transactions'])['payment_method'];
            $paymentMethods = [
                $this->getShortMethodCode(Afterpay::METHOD_CODE),
                $this->getShortMethodCode(Klarna::METHOD_CODE)
            ];

            if (in_array($method, $paymentMethods))
            {
                $methodForMessage = ($method == $this->getShortMethodCode(Afterpay::METHOD_CODE)) ? 'Afterpay' : 'Klarna';

                return (string) __('Unfortunately, we can not currently
                accept your purchase with '.$methodForMessage.'. Please choose another payment
                option to complete your order. We apologize for the inconvenience.');
            }
        }
```
(It's just example)

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ControllerCheckoutActionBuilder.php
> +            }
unnecessary else statement, because there we have 'early return', and !empty($var) can be replaced by just $var. For example it can be simplified in the next way:
```
if ($status['success'])
{
    $this->checkoutSession->start();
    return $this->_redirect('checkout/onepage/success?utm_nooverride=1');
}

$this->checkoutSession->restoreQuote();

if ($status['cart_msg']) {
    $this->messageManager->addNoticeMessage($status['cart_msg']);
} else {
    $this->messageManager->addNoticeMessage(__('Something went wrong.'));
}
```

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ControllerCheckoutActionBuilder.php
> +            if (!empty($result['error'])) {
condition if(!empty($var)) can be simplified just by if($var), take a [look](https://www.php.net/manual/en/types.comparisons.php), there is table with types comparisons

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/LibraryConfigProvider.php
> +        }
it can be simplified in the next way: 
`        $activeMethods = ($client = $this->paymentLibraryModel->loadGingerClient()) ? $this->getActiveMethods() : [];
`
(it's example, and just in case should be tested)

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/LibraryConfigProvider.php
> +            if (!empty($this->methods[$code]) && $this->methods[$code]->isAvailable()) {
!empty($var) also can be simplified by just $var

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/LibraryConfigProvider.php
> +                }
Can be simplified by two ways: 

- `$config['payment'][$code]['isActive'] = in_array($code, $activeMethods) ? true : false;`
- `$config['payment'][$code]['isActive'] = in_array($code, $activeMethods);`

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/LibraryConfigProvider.php
> +            }
We can avoid this else statement, for this use 'early return' and we should place code from 'else' statement firstly, but with inversion condition from 'if':
`if (!$this->methods[$code] && !$this->methods[$code]->isAvailable())
  {
      $config['payment'][$code]['isActive'] = false;
      return $config;
  }` 
  and after place code from 'if', it will be looks like:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/80386578/144231118-f2f05b9a-fef1-48c2-87de-9380efb69721.png">

(it's example and should be tested)

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/TransactionBuilder.php
> +////        }
Why code is commented?

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Methods/KlarnaDirect.php
> +class KlarnaDirect extends PaymentLibraryRedefiner
Probably it's should be KlarnaPayNow

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/Methods/KlarnaDirect.php
> +    const METHOD_CODE = 'ginger_methods_klarnadirect';
Probably it's should be klarnapaynow

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/PaymentLibrary.php
> +                }
While latest reviewing of WooCommerce plugin, was decided to add default currency "EUR" in each case of exception, therefore 'if' statement is unnecessary

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/PaymentLibrary.php
> +        }
unnecessary 'else' statement that can be replaced by 'early return', for example:

```
if($this->checkoutSession->getMultiCurrency()) {
    if (!array_key_exists($this->platform_code, $this->checkoutSession->getMultiCurrency()['payment_methods'])) return false;
    $currencyForCurrentPayment = $this->checkoutSession->getMultiCurrency()['payment_methods'][$this->platform_code]['currencies'];
  } else {
      $currencyForCurrentPayment = ['EUR'];
  }
```

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/PaymentLibrary.php
> +        }
But it's still looks like it can be simplified another one time, probably you find way to avoid 'else' statement

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Model/PaymentLibrary.php
> +            $reason = current($gingerOrder['transactions'])['reason'] ?? 'Refund order is not completed';
reason should be replaced by customer_message key

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Tests/CreateOrderTest.php
> +                "plugin_name" => "ems-online-magento-2",
as Tests folder it's main functionality, there is shouldn't be ems-online prefix, we have to find another way to test "plugin_name"

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on Tests/CreateOrderTest.php
> +            "plugin_name" => "ems-online-magento-2",
the same moment about "ems-online" prefix

2021-12-01 13:49 UTC, Denis-Tsyganok-Leasoft commented on etc/adminhtml/methods/klarnadirect.xml
> +            <config_path>payment/ginger_methods_klarnadirect/title</config_path>
file name klarnadirect, but we also have klarnadirectdebit, probably one of them is Klarna Pay now

2021-12-02 10:56 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ControllerCheckoutActionBuilder.php
> +            }
if/else condition also can be simplified 
```
$message = $status['cart_msg'] ? $status['cart_msg'] : __('Something went wrong.');
 $this->messageManager->addNoticeMessage($message)
```

2021-12-13 13:53 UTC, Denis-Tsyganok-Leasoft commented on Model/Builders/ControllerCheckoutActionBuilder.php
> +            }
$this->messageManager->addNoticeMessage($status['cart_msg'] ?? __('Something went wrong.'));

OR

$message = $status['cart_msg'] ?? __('Something went wrong.');
$this->messageManager->addNoticeMessage($message)

2021-12-14 12:01 UTC, tiutiunnykleasoft requested changes
tikkie is tikkie payment request payment method

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Api/Config/RepositoryInterface.php
> +     * @param string $payment
deprecated variable, look at arguments in function definition

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Api/Config/RepositoryInterface.php
> +    public function getApiKey(int $storeId);
return type could be established using `?` prefix, it's means that the return value could be typed or null. in this case `: ?string`

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Block/Adminhtml/Render/Header.php
> +namespace GingerPay\Payment\Block\Adminhtml\Render;
Emspay and GingerPay it's not similar thing, emspay we used for EMS only, for Ginger suggestion to use GingerPayments instead

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Controller/Adminhtml/Action/Apikey.php
> +            $client = $this->client->get((int)$storeId, $apiKey);
What a reason to providing storeId and apiKey in this way?
In GingerClient constructor determined the ConfigRepository, so i thought you could get config params inside GingerClient.

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Controller/Adminhtml/Action/Apikey.php
> +                $success = false;
Did you have a reason to continue function execution without returning value there?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Controller/Checkout/Process.php
> +        ConfigRepository $configRepository
In PaymentLibraryModel you also have a ConfigRepository, what a reason to duplicate objects definition ?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Controller/Checkout/Webhook.php
> +        $this->resultFactory = $context->getResultFactory();
Compare with 50 line

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Logger/DebugLogger.php
> + * Logger Class for Debug Logger
Could you clarify why the Logger class if for Debug Logger, as i see it's a Debug Logger for Logger. Anyway the comment not informative at all, remove or rewrite

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Logger/ErrorLogger.php
> +class ErrorLogger extends Logger
What a difference between this class and DebugLogger?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/Adminhtml/Source/ApiKey.php
> + * ApiKey source class
Not informative

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/Builders/ApiBuilder.php
> +require_once __DIR__ ."/../../Library/vendor/autoload.php";
As far as there no static function, we don't need to load autoload file before ApiBuilder uses. Is it possible to add this require to constructor of the ApiBuilder?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/Builders/ConfigRepositoryBuilder.php
> +        $active = $this->getStoreConfig(self::XML_PATH_MODULE_ACTIVE);
For what this variable, if the value using only once?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/Builders/ConfigRepositoryBuilder.php
> +     * {@inheritDoc}
What a reason to presenting such comment?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/Builders/LibraryConfigProvider.php
> +                $config['payment'][$code]['instructions'] = $this->getInstructions($code);
in all cases down from there uses such array element as `$config[payment][code]`, maybe better to create variable for it?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/Builders/ServiceOrderBuilder.php
> +        $customerData = [
add `array_filter()` there to remove null values

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/Builders/ServiceOrderLinesBuilder.php
> +        return preg_replace("/[^A-Za-z0-9 ]/", "", $item->getName());
Could you describe reason to change original item name?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/AbstractPayment.php
> +        {
Should you replace this statement by analog with early return principle?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/AbstractPayment.php
> +     * @return $this->testApiKey
Thats true

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Model/PaymentLibrary.php
> +    protected $client = null;
Should you establish default values inside constructor?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Service/Transaction/Process/Cancelled.php
> +class Cancelled extends AbstractTransaction
Could you provide a reason to creating 7 classes only with difference in one variable value?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Tests/ClassSeparators/ConfigRepositoryBuilderSeparator.php
> +        return '1.1.0';
Is it testing original function workability ?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Tests/Mocks/Customer.php
> +    public static function getCustomerData()
Also will be good to test each function with its original realisation

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on Tests/Mocks/Order.php
> +    }
If the original realisations changes, we be changes tested by such tests?

2021-12-14 12:01 UTC, tiutiunnykleasoft commented on registration.php
> + * Copyright © Magmodules.eu. All rights reserved.
Copyright is now assigned to Ginger

2021-12-14 14:45 UTC, Denis-Tsyganok-Leasoft reviewed
1. Add notify message to checkout when some payment methods don't accept chosen currencies (probably add some message with list of payment methods that don't accept the currency)
2. While testing webhook I've faced with error (img attached), you can find information about webhook [here](https://dev.online.emspay.eu/rest-api/features/webhooks)
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/80386578/146020216-2838ae97-08c0-4eff-9738-98cf6b3ee670.png">

2021-12-15 11:04 UTC, BohdanLeasoft commented on Model/PaymentLibrary.php
> +    protected $client = null;
It looks like magento developers are doing it in this way

In AbstractMethod.php which is default magento file this variables defined in this way
`  /**
     * Payment Method feature
     *
     * @var bool
     */
    protected $_isGateway = false;

    /**
     * Payment Method feature
     *
     * @var bool
     */
    protected $_isOffline = false;

    /**
     * Payment Method feature
     *
     * @var bool
     */
    protected $_canOrder = false;`

Could you clarify is it possible to leave the definition as it is?

2021-12-15 11:10 UTC, BohdanLeasoft commented on Model/Builders/ConfigRepositoryBuilder.php
> +     * {@inheritDoc}
Magento marketplace is request from developers using  PHP_CodeSniffer. If i get it correct this `{@inheritDoc}` is something like placeholder. Do I need to change it?

2021-12-15 11:17 UTC, BohdanLeasoft commented on Logger/ErrorLogger.php
> +class ErrorLogger extends Logger
If I not mistaken, DebugLogger sholud write more information, but it do not work in production mode.

2022-03-21 13:21 UTC, closed without merging